version: "3"

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - api_db_network

  web:
    build: ../telegram_bot_api/
    command: bash -c "cd app/ && ls && cd telegram_bot_api/ && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ..:/app
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - api_bot_network
      - api_db_network

  bot:
    image: ${DOCKER_USERNAME}/tg_bot:latest
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - api_bot_network

networks:
  api_bot_network:
  api_db_network:
