version: "3"

services:
  db:
    image: postgres:11
    ports:
      - ${DB_PORT}:${{ secrets.DB_PORT }}
    environment:
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - DB_NAME=${{ secrets.DB_NAME }}
    networks:
      - api_db_network

  web:
    image: ${{ secrets.DOCKER_USERNAME }}/fastapi_tg_bot:latest
    command: bash -c "cd ../app/telegram_bot_api/ && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ..:/app
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - api_bot_network
      - api_db_network

  bot:
    image: ${{ secrets.DOCKER_USERNAME }}/tg_bot:latest
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - api_bot_network

networks:
  api_bot_network:
  api_db_network:
