version: "3"

services:
  db:
    image: postgres:11
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  web:
    build: ../telegram_bot_api/
    command: bash -c "cd ../app/telegram_bot_api/ && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ..:/app
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db

  bot:
    build: ../telegram_bot/
    env_file:
      - .env
    depends_on:
      - web


#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db