"""Migration
Revision ID: 92b879ffc352
Revises:
Create Date: 2022-08-05 07:26:32.511677
"""

revision = '92b879ffc352'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
